project:
  type: website
  # output-dir: docs

website:
  navbar:
    search: true
    collapse: false
    background: "#f7eee1"
    foreground: "#1a029e"
    left:
      - href: index.qmd
        text: home
      - href: projects.qmd
        text: projects
    right:
      - icon: github
        text: maniacalwhistle
        href: https://github.com/maniacalwhistle
      - icon: camera
        text: photos
        href: https://maniacalwhistle.github.io/foto.maniacalwhistle.us

format:
  html:
    theme: cosmo
    backgroundcolor: "#f7eee1"
    css: styles.css
    toc: true
